# Generated by Django 3.1.4 on 2021-04-17 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycofee', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
